# Generated by Django 3.1.5 on 2021-01-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0002_auto_20210120_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='minutesid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resourcedate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resourcetext',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resourcetime',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resourceurl',
            new_name='url',
        ),
    ]
